---
- name: Install dependencies
  ansible.builtin.apt:
    pkg:
      - "python3-debian"

- name: Remove old tailscale apt configuration
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/apt/sources.list.d/tailscale.list"

- name: Add tailscale apt repository
  ansible.builtin.deb822_repository:
    name: tailscale
    uris: "{{ tailscale_apt_repo_url }}"
    suites: "{{ tailscale_apt_repo_suite }}"
    components: "{{ tailscale_apt_repo_component }}"
    signed_by: "{{ tailscale_apt_repo_gpg_key }}"
    state: present
  register: _apt_repo

- name: Install tailscale
  ansible.builtin.apt:
    pkg: "{{ tailscale_packages }}"
    install_recommends: false
    update_cache: "{{ true if _apt_repo is changed else false }}"
    state: present
