---
- name: Install tailscale
  ansible.builtin.import_tasks:
    file: install.yml

- name: Configure tailscale
  ansible.builtin.import_tasks:
    file: config.yml

- name: Set facts
  ansible.builtin.import_tasks:
    file: facts.yml

- name: Configure tailscale serve
  ansible.builtin.include_tasks:
    file: serve.yml
  when: tailscale_serve | length >= 1
