---
- name: Converge
  hosts: all
  tasks:
    - name: "Include wandansible.tailscale"
      ansible.builtin.include_role:
        name: "wandansible.tailscale"
      vars:
        tailscale_config:
          AcceptDNS: true
          RunSSHServer: true
          AutoUpdate:
            Check: true
            Apply: true

        tailscale_args:
          - option: "advertise-tags"
            value: "tag:web-server,tag:ssh-server"

        tailscale_tailscaled_env_vars:
          - name: "TS_DEBUG_FIREWALL_MODE"
            value: "nftables"
          - name: "TS_PERMIT_CERT_UID"
            value: "caddy"
